packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  leveldown: set this to true or false
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - leveldown
  - msgpackr-extract
  - prisma
